package com.microsoft.azure.webjobs.script.handler;

import java.util.function.*;
import java.util.logging.Level;

import com.google.protobuf.*;
import com.microsoft.azure.webjobs.script.*;
import com.microsoft.azure.webjobs.script.rpc.messages.*;

public abstract class MessageHandler<TRequest extends Message, TResponse extends Message.Builder> {
    MessageHandler(Function<StreamingMessage, TRequest> requestMarshaller,
                   Supplier<TResponse> responseSupplier,
                   BiConsumer<TResponse, StatusResult> responseStatusMarshaller,
                   BiConsumer<StreamingMessage.Builder, TResponse> responseMarshaller) {
        this.requestMarshaller = requestMarshaller;
        this.responseSupplier = responseSupplier;
        this.responseStatusMarshaller = responseStatusMarshaller;
        this.responseMarshaller = responseMarshaller;
    }

    public MessageHandler<TRequest, TResponse> setRequest(StreamingMessage message) {
        this.request = this.requestMarshaller.apply(message);
        return this;
    }

    public StreamingMessage.Builder marshalResponse(StreamingMessage.Builder message) {
        this.responseMarshaller.accept(message, this.response);
        return message;
    }

    public MessageHandler<TRequest, TResponse> handle() {
        StatusResult.Status status = StatusResult.Status.Success;
        String statusMessage;
        try {
            this.response = this.responseSupplier.get();
            statusMessage = this.execute(this.request, this.response);
            Application.LOGGER.info(statusMessage);
        } catch (Exception ex) {
            status = StatusResult.Status.Failure;
            statusMessage = ex.getMessage();
            Application.LOGGER.log(Level.WARNING, statusMessage, ex);
        }
        if (this.responseStatusMarshaller != null) {
            StatusResult result = StatusResult.newBuilder().setStatus(status).setResult(statusMessage).build();
            this.responseStatusMarshaller.accept(this.response, result);
        }
        return this;
    }

    abstract String execute(TRequest request, TResponse response) throws Exception;

    private TRequest request = null;
    private TResponse response = null;
    private Function<StreamingMessage, TRequest> requestMarshaller;
    private Supplier<TResponse> responseSupplier;
    private BiConsumer<TResponse, StatusResult> responseStatusMarshaller;
    private BiConsumer<StreamingMessage.Builder, TResponse> responseMarshaller;
}

abstract class OutboundMessageHandler<T extends Message.Builder> extends MessageHandler<Message, T> {
    OutboundMessageHandler(Supplier<T> responseSupplier, BiConsumer<StreamingMessage.Builder, T> responseMarshaller) {
        super(null, responseSupplier, null, responseMarshaller);
        super.handle();
    }

    @Override
    String execute(Message message, T response) { return "message generated by \"" + response.getClass() + "\""; }
}
