trigger:
  branches:
    include:
    - dev
    - release/* # azure-functions-java-worker github repo restricts creation of release/* branches, so using a pattern is safe here.
    - shreyasg/icm-496768690-threadctx-removed

resources:
  repositories:
  - repository: eng
    type: git
    name: engineering
    ref: refs/tags/release

variables:
  - template: ci/variables/cfs.yml@eng

extends:
  template: ci/code-mirror.yml@eng
