parameters:
  - name: poolName
    type: string
    default: ''

jobs:
  - job: "TestWindows"
    displayName: 'Test java worker - Windows'

    pool:
      name: ${{ parameters.poolName }}
      image: 1es-windows-2022
      os: windows

    variables:
      - template: ../java-versions.yml
      - ${{ if contains(variables['Build.SourceBranch'], '/tags/' ) }}:
        - name: isTagTemp
          value: true
      - name: isTag
        value: $[variables.isTagTemp]

    strategy:
      maxParallel: 4
      matrix:
        open-jdk-8-windows:
          JDK_DOWNLOAD_LINK: 'https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u$(JDK8_WINDOWS_VERSION)-b$(JDK8_WINDOWS_BUILD)/OpenJDK8U-jdk_x64_windows_hotspot_8u$(JDK8_WINDOWS_VERSION)b$(JDK8_WINDOWS_BUILD).zip'
          JAVA_VERSION: 'OpenJDK8U-jdk_x64_windows_hotspot_8u$(JDK8_WINDOWS_VERSION)b$(JDK8_WINDOWS_BUILD)'
          JAVA_VERSION_SPEC: '8'
        microsoft-open-jdk-11-windows:
          JDK_DOWNLOAD_LINK: 'https://aka.ms/download-jdk/microsoft-jdk-$(JDK11_WINDOWS_VERSION)-windows-x64.zip'
          JAVA_VERSION: 'microsoft-jdk-$(JDK11_WINDOWS_VERSION)-windows-x64'
          JAVA_VERSION_SPEC: '11'
        microsoft-open-jdk-17-windows:
          JDK_DOWNLOAD_LINK: 'https://aka.ms/download-jdk/microsoft-jdk-$(JDK17_WINDOWS_VERSION)-windows-x64.zip'
          JAVA_VERSION: 'microsoft-jdk-$(JDK17_WINDOWS_VERSION)-windows-x64'
          JAVA_VERSION_SPEC: '17'
        microsoft-open-jdk-21-windows:
          JDK_DOWNLOAD_LINK: 'https://aka.ms/download-jdk/microsoft-jdk-$(JDK21_WINDOWS_VERSION)-windows-x64.zip'
          JAVA_VERSION: 'microsoft-jdk-$(JDK21_WINDOWS_VERSION)-windows-x64'
          JAVA_VERSION_SPEC: '21'
        microsoft-open-jdk-25-windows:
          JDK_DOWNLOAD_LINK: 'https://aka.ms/download-jdk/microsoft-jdk-$(JDK25_WINDOWS_VERSION)-windows-x64.zip'
          JAVA_VERSION: 'microsoft-jdk-$(JDK25_WINDOWS_VERSION)-windows-x64'
          JAVA_VERSION_SPEC: '25'

    steps:
      - task: NuGetToolInstaller@1
        inputs:
          checkLatest: true
        displayName: 'Install NuGet Tool'
      - pwsh: |
          Get-Command mvn
        displayName: 'Check Maven is installed'
      - pwsh: |
          java -version
        displayName: 'Check default java version'
      - task: UseDotNet@2
        displayName: 'Install .NET 6'
        inputs:
          version: 6.0.x
      - pwsh: | # Download JDK for later installation
          Invoke-WebRequest $(JDK_DOWNLOAD_LINK) -OutFile "$(JAVA_VERSION).zip"
          $current = get-location | select -ExpandProperty Path
          Write-Host "##vso[task.setvariable variable=downloadPath;]$current"
        displayName: 'Download jdk for Windows'
      - task: JavaToolInstaller@0 # Install JDK downloaded from previous task
        inputs:
          versionSpec: $(JAVA_VERSION_SPEC)
          jdkArchitectureOption: 'x64'
          jdkSourceOption: LocalDirectory
          jdkFile: "$(downloadPath)/$(JAVA_VERSION).zip"
          jdkDestinationDirectory: "$(downloadPath)/externals"
          cleanDestinationDirectory: true
        displayName: 'Setup Java for Windows'
      - bash: |
          npm install -g azurite
          mkdir azurite
          azurite --silent --location azurite --debug azurite\debug.log &
        displayName: 'Install and Run Azurite'
      - pwsh: |
          if ("$(isTag)"){
            $buildNumber="$(Build.SourceBranchName)"
            Write-Host "Found git tag."
          }
          else {
            $buildNumber="$(Build.BuildNumber)-v4"
            Write-Host "git tag not found. Setting package suffix to '$buildNumber'"
          }
          Write-Host "##vso[task.setvariable variable=buildNumber;isOutput=true;]$buildNumber"
          .\package-pipeline.ps1 -buildNumber $buildNumber
        displayName: 'Executing build script'
      - pwsh: |
          # Download Mozilla CA certificate bundle
          Invoke-WebRequest -Uri "https://curl.se/ca/cacert.pem" -OutFile "./emulatedtests/confluent_cloud_cacert.pem"
          cd ./emulatedtests
          mvn clean package `-Dmaven`.javadoc`.skip=true `-Dmaven`.test`.skip `-Dorg`.slf4j`.simpleLogger`.log`.org`.apache`.maven`.cli`.transfer`.Slf4jMavenTransferListener=warn `-B
          Copy-Item "confluent_cloud_cacert.pem" "./target/azure-functions/azure-functions-java-emulatedtests"
        displayName: 'Download CA Bundle & Package Java for Emulated Tests'
      - pwsh: |
          .\setup-tests-pipeline.ps1
        displayName: 'Setup test environment -- Install the Core Tools'
      - pwsh: |
          $currDir =  Get-Location
          $Env:Path = $Env:Path+";$currDir/Azure.Functions.Cli"
          func --version
        displayName: 'Setup Core Tools - Windows'
      - task: DotNetCoreCLI@2
        retryCountOnTaskFailure: 3
        inputs:
          command: 'test'
          projects: |
            emulatedtests/Azure.Functions.Java.Tests.E2E/Azure.Functions.Java.Tests.E2E/Azure.Functions.Java.Tests.E2E.csproj
        env:
          AzureWebJobsStorage: "UseDevelopmentStorage=true"
        displayName: 'Build & Run tests'
        continueOnError: false